package Frame_Utama;

import LoginForm.LoginForm;
import Panel.PanelAbout;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class FrameUtama extends javax.swing.JFrame {

    public JPopupMenu popup = null;
    public static FrameUtama menu=null;
    private PanelDokter panelDokter;
    private PanelPasien panelPasien;
    private PanelPerawat panelPerawat;
    private PanelRekam panelRekam;
    private PanelRuangan panelRuangan;
    private MainMenu panelMain;
    private PanelAbout panelAbout;
    
    /**
     * Creates new form FrameUtama
     */
    public FrameUtama() {
        super("Sistem Informasi Rekam Medis");
        setResizable(false);
   
        initComponents();
        this.setLocationRelativeTo(null);
        panelMain=new MainMenu();
        PanelUtama.add("panelMain",panelMain);
        showPanel("panelMain");
    }
    //Membuat tampilan pada panel
    private void showPanel(String panelIdentifier){
        CardLayout cardLayout = (CardLayout) PanelUtama.getLayout();
        cardLayout.show(PanelUtama, panelIdentifier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem22 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelUtama.setLayout(new java.awt.CardLayout());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/194.png"))); // NOI18N
        jMenu1.setText("Menu");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/124.png"))); // NOI18N
        jMenuItem6.setText("Halaman Utama");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator1);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Car key.png"))); // NOI18N
        jMenuItem7.setText("Login");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);
        jMenu1.add(jSeparator2);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/17.png"))); // NOI18N
        jMenuItem8.setText("Keluar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/18.png"))); // NOI18N
        jMenu2.setText("Master Data");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/47.png"))); // NOI18N
        jMenuItem9.setText("Data Dokter");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/47.png"))); // NOI18N
        jMenuItem10.setText("Data Pasien");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/47.png"))); // NOI18N
        jMenuItem11.setText("Data Perawat");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/160.png"))); // NOI18N
        jMenuItem12.setText("Data Ruangan");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);
        jMenu2.add(jSeparator3);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/149.png"))); // NOI18N
        jMenuItem13.setText("Data Rekam Medis");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);
        jMenu2.add(jSeparator4);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/24.png"))); // NOI18N
        jMenuItem16.setText("Data Hasil Diagnosa & Laboratorium");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenuBar1.add(jMenu2);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/136.png"))); // NOI18N
        jMenu6.setText("Cetak Laporan");

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/132.png"))); // NOI18N
        jMenuItem17.setText("Data Pasien");
        jMenu6.add(jMenuItem17);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/132.png"))); // NOI18N
        jMenuItem18.setText("Data Ruang");
        jMenu6.add(jMenuItem18);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/132.png"))); // NOI18N
        jMenuItem19.setText("Data Dokter");
        jMenu6.add(jMenuItem19);

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/132.png"))); // NOI18N
        jMenuItem21.setText("Data Perawat");
        jMenu6.add(jMenuItem21);
        jMenu6.add(jSeparator9);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/137.png"))); // NOI18N
        jMenuItem22.setText("Data Rekam Medis");
        jMenu6.add(jMenuItem22);
        jMenu6.add(jSeparator10);

        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/132.png"))); // NOI18N
        jMenuItem23.setText("Data Hasil Diagnosa & Laboratorium");
        jMenu6.add(jMenuItem23);

        jMenuBar1.add(jMenu6);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/179.png"))); // NOI18N
        jMenu4.setText("Bantuan");

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/138.png"))); // NOI18N
        jMenuItem15.setText("Bantuan Penggunaan");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/191.png"))); // NOI18N
        jMenu5.setText("Tentang");

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/154.png"))); // NOI18N
        jMenuItem14.setText("Tentang Program");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Terimakasih\n", "Pesan", 1);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        panelMain=new MainMenu();
        PanelUtama.add("panelMain",panelMain);
        showPanel("panelMain");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        panelDokter=new PanelDokter();
        PanelUtama.add("panelDokter",panelDokter);
        showPanel("panelDokter");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        panelPasien=new PanelPasien();
        PanelUtama.add("panelPasien",panelPasien);
        showPanel("panelPasien");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        panelPerawat=new PanelPerawat();
        PanelUtama.add("panelPerawat",panelPerawat);
        showPanel("panelPerawat");
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        panelRuangan=new PanelRuangan();
        PanelUtama.add("panelRuangan",panelRuangan);
        showPanel("panelRuangan");
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        panelRekam=new PanelRekam();
        PanelUtama.add("panelRekam",panelRekam);
        showPanel("panelRekam");
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        LoginForm fml=new LoginForm();
        fml.setVisible(true);
        //JOptionPane.showMessageDialog(this, "Log Out Berhasil","Sukses",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        //panelHasilDiagnosa=new PanelHasilDiagnosa();
        //PanelUtama.add("panelHasilDiagnosa",panelHasilDiagnosa);
        showPanel("panelHasilDiagnosa");
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        //panelBantuan=new PanelBantuan();
        //PanelUtama.add("panelBantuan",panelBantuan);
        showPanel("panelBantuan");
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        panelAbout=new PanelAbout();
        PanelUtama.add("panelAbout",panelAbout);
        showPanel("panelAbout");
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        menu=new FrameUtama();
    menu.setVisible(true);
    }
            //</editor-fold>

        /*
         * Create and display the form
         */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
